### ISSUE TITLE
Cannot send mails due to ignore_target_hosts parameter

### ISSUE THREAD

**Issue by landauermax** [ait-cs-IaaS/ansible-exim#1]
I was unable to send mails between mail servers and got the following message in the logs:

`all relevant MX records point to non-existent hosts`

I eventually found [this issue](https://github.com/namshi/docker-smtp/issues/65) and was able to resolve the problem by commenting out the ignore_target_hosts parameter of the exim configuration.

**Comment by b3n4kh** [comment]
Maybe we add an option to ignore all non RFC1918 adresses.
